package ai.xdigit.ragchatstorage.model;

/**
 * Discriminator enum that identifies the originator of a {@link ChatMessage}.
 *
 * <p>Stored as a {@code VARCHAR(20)} column in the {@code chat_messages} table using
 * {@code EnumType.STRING}, so the persisted value is the literal enum name
 * ({@code "USER"} or {@code "ASSISTANT"}).
 *
 * @see ChatMessage
 */
public enum Sender {

    /**
     * The message was authored by the human user interacting with the chat interface.
     */
    USER,

    /**
     * The message was generated by the AI assistant (language model), optionally
     * augmented with retrieved context stored in {@link ChatMessage#getRetrievedContext()}.
     */
    ASSISTANT
}
